from datetime import date, datetime
from typing import Optional
from pydantic import BaseModel, EmailStr, field_validator
from app.models.user import UserRole, TeamType, ContractType


class UserBase(BaseModel):
    full_name: str
    email: EmailStr
    phone: Optional[str] = None
    role: UserRole = UserRole.MEMBER
    team: Optional[TeamType] = None
    main_business_id: Optional[int] = None
    secondary_business_id: Optional[int] = None
    contract_start_date: Optional[date] = None
    contract_type: Optional[ContractType] = None
    contract_renewal_date: Optional[date] = None

    @field_validator("contract_renewal_date")
    @classmethod
    def validate_renewal_date(cls, v, info):
        if info.data.get("contract_type") == ContractType.INDEFINIDO and v is not None:
            raise ValueError("Los contratos indefinidos no tienen fecha de renovación")
        return v


class UserCreate(UserBase):
    pass  # Password is auto-generated by admin


class UserUpdate(BaseModel):
    full_name: Optional[str] = None
    phone: Optional[str] = None
    role: Optional[UserRole] = None
    team: Optional[TeamType] = None
    main_business_id: Optional[int] = None
    secondary_business_id: Optional[int] = None
    contract_start_date: Optional[date] = None
    contract_type: Optional[ContractType] = None
    contract_renewal_date: Optional[date] = None
    is_active: Optional[bool] = None
    avatar_url: Optional[str] = None


class BusinessInfo(BaseModel):
    id: int
    name: str
    color: str

    class Config:
        from_attributes = True


class UserCreateResponse(BaseModel):
    """Response for POST /users — includes temp_password so admin can share it."""
    id: int
    full_name: str
    email: str
    phone: Optional[str] = None
    role: UserRole
    team: Optional[TeamType] = None
    main_business: Optional[BusinessInfo] = None
    secondary_business: Optional[BusinessInfo] = None
    contract_type: Optional[ContractType] = None
    is_active: bool
    must_change_password: bool
    temp_password: str = ""

    model_config = {"from_attributes": True}


class UserResponse(BaseModel):
    id: int
    full_name: str
    email: str
    phone: Optional[str] = None
    role: UserRole
    team: Optional[TeamType] = None
    main_business: Optional[BusinessInfo] = None
    secondary_business: Optional[BusinessInfo] = None
    contract_start_date: Optional[date] = None
    contract_type: Optional[ContractType] = None
    contract_renewal_date: Optional[date] = None
    is_active: bool
    avatar_url: Optional[str] = None
    must_change_password: bool
    last_login: Optional[datetime] = None
    created_at: datetime

    class Config:
        from_attributes = True


class UserListResponse(BaseModel):
    id: int
    full_name: str
    email: str
    role: UserRole
    team: Optional[TeamType] = None
    is_active: bool
    avatar_url: Optional[str] = None
    main_business: Optional[BusinessInfo] = None

    class Config:
        from_attributes = True
